use_frameworks!

target 'test_Example' do
  pod 'test', :path => '../test.podspec'

  target 'test_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
